-- No-op: 0004_app_schedules.sql already creates columns with the final names
-- (blocking_start_time / blocking_end_time). This migration was only needed
-- for databases created before 0004 used those names directly.
